var dbAdapter = require("./dbAdapter");

var statusCodes = [
    "616|Revived-Awaiting Further Action|Law Office|Law_Office",
    "630|New Application-Record initialized not assigned to Law Office examiner|Law Office|Law_Office",
    "638|New Application-Assigned to an examiner|Law Office|Law_Office",
    "640|Non-final action counted-Not mailed|Law Office|Law_Office",
    "641|Non-final action-Mailed|Law Office|Law_Office",
    "643|Previous action/approval count withdrawn|Law Office|Law_Office",
    "644|Final refusal counted-Not mailed|Law Office|Law_Office",
    "645|Final refusal-Mailed|Law Office|Law_Office",
    "646|Examiner's amendment counted-Not mailed|Law Office|Law_Office",
    "647|Examiner's amendment-Mailed |Law Office|Law_Office",
    "648|Action continuing Final counted-Not mailed |Law Office|Law_Office",
    "649|Action continuing Final-Mailed|Law Office|Law_Office",
    "650|Suspension inquiry counted-Not mailed|Law Office|Law_Office",
    "651|Suspension inquiry-Mailed|Law Office|Law_Office",
    "652|Suspension letter counted-Not mailed |Law Office|Law_Office",
    "653|Suspension letter-Mailed|Law Office|Law_Office",
    "654|Report completed suspension check-Case still suspended|Law Office|Law_Office",
    "661|Response after non-Final action-Entered|Law Office|Law_Office",
    "663|Response after Final rejection-Entered|Law Office|Law_Office",
    "665|Notice of unresponsive amendment-Counted|Law Office|Law_Office",
    "666|Notice of unresponsive amendment-Mailed|Law Office|Law_Office",
    "667|Refusal withdrawal letter-Counted|Law Office|Law_Office",
    "668|Refusal withdrawal letter-Mailed |Law Office|Law_Office",
    "672|Reinstated-Awaiting further action |Law Office|Law_Office",
    "680|Approved for publication|Law Office|Law_Office",
    "693|Withdrawn from registration-Jurisdiction restored|Law Office|Law_Office",
    "715|Cancelled-Restored to Pendency|Law Office|Law_Office",
    "747|Statement of Use-ITU processing complete|Law Office|Law_Office",
    "748|Statement of Use-To examiner |Law Office|Law_Office",
    "752|Statement of Use-Examiner statement counted-Not mailed|Law Office|Law_Office",
    "753|Statement of Use-Examiner Statement-Mailed|Law Office|Law_Office",
    "756|Examiner statement counted-Not mailed|Law Office|Law_Office",
    "757|Examiner statement-Mailed|Law Office|Law_Office",
    "794|Jurisdiction restored to examiner|Law Office|Law_Office",
    "601|Abandoned-Express|Warehouse|Warehouse|Warehouse",
    "602|Abandoned-Failure to Respond|Warehouse|Warehouse",
    "603|Abandoned-After ex parte Appeal|Warehouse|Warehouse",
    "604|Abandoned-After inter partes decision|Warehouse|Warehouse",
    "605|Abandoned-After Publication|Warehouse|Warehouse",
    "606|Abandoned-No Statement of Use filed|Warehouse|Warehouse",
    "607|Abandoned-Defective Statement of use|Warehouse|Warehouse",
    "608|Abandoned-After Petition Decision|Warehouse|Warehouse",
    "609|Abandoned-Defective Divided Application|Warehouse|Warehouse",
    "612|Petition to Revive-received|TMEO Dir|TMEO_Dir",
    "622|Misassigned Serial Number|File Cover Destroyed|File_Cover_Destroyed",
    "631|New Application-Divided-Initial processing|ITU Unit|ITU_Unit",
    "632|Informal Application|Pre-Exam|Pre_Exam",
    "681|Publication/Registration review complete|Pub. and Issue|Pub_Issue",
    "686|Published for Opposition|Pub. and Issue|Pub_Issue",
    "701|Section 8-Accepted|Post Reg.|Post_Reg",
    "702|Section 8 and 15-accepted and acknowledged|Post Reg.|Post_Reg",
    "703|Section 15-acknowledged|Post Reg.|Post_Reg",
    "704|Partial Section 8 accepted|Post_Reg.|Post_Reg",
    "763|Ex parte appeal-Refusal affirmed|TTAB|TTAB",
    "764|Ex parte appeal dismissed as moot|TTAB|TTAB",
    "765|Concurrant use proceeding terminated-Granted|TTAB|TTAB",
    "766|Concurrant use proceeding terminated-Denied|TTAB|TTAB"
];

dbAdapter.insertStatusCodes(statusCodes);




